### ISSUE TITLE
Harmonize query naming

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Model-Explorer#12]
Query naming is inconsistent in sparql/queries.js and sparql/documented-queries.js:
. Some queries use UpperCamelCase (GSIMGroups), others lowerCamelCase (gsimInputServices) --> harmonize on UCC
. Some queries put the return resource as prefix (serviceBySubProcess, should be servicesBySubprocess), others as suffix (gsimInputServices) --> harmonize on prefix (plural + 'by')

**Comment by ghost** [comment]
When we take into account the two rules, the resulting renamings are:
- gsimInputServices ->   servicesByGSIMInput
- gsimOutputServices ->  servicesByGSIMOutput
- serviceBySubProcess ->  servicesBySubProcess
