### ISSUE TITLE
Enrich GSBPM sub-process page

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Model-Explorer#13]
Currently, when one clicks on a GSBPM sub-process, one gets a list of services operating in this sub-process, or a 'sorry' message if there are none.
This page should in fact give details on the selected GSBPM sub-process, with the name and description of the sub-process (skos:prefLabel and skos:definition), the list of CSPA services (if any), and other things to come (quality indicators, etc.).

**Comment by ghost** [comment]
Done with 4f94e7f657b3c468d7729e0723463400b7ce67ad
