### ISSUE TITLE
Enrich GSIM object page

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Model-Explorer#14]
Currently, when one clicks on a GSIM object, one gets a list of services with this object as input or output (or a 'sorry' message if there are none).
This page should in fact give details on the selected GSIM object, with the name and description of the object, the list of CSPA services taking the object as input (if any), the list of CSPA services taking the object as output (if any), and other things to come (link to clickable GSIM, etc.).

**Comment by ghost** [comment]
Done with ce189ea520760da7630f4e17daed1bd67cc41285
