### ISSUE TITLE
Manage main menu

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Model-Explorer#15]
Main menu should display a hover effect and the current page should be highlighted.

**Comment by ghost** [comment]
This behavior sounds like a mix between bootstrap `navbar` and `nav-pills`. The second looks like this, which is not exactly what we're looking for (CSPA Service App should appear as the "brand" in bootstrap terminology).

![screen shot 2016-11-09 at 15 05 41](https://cloud.githubusercontent.com/assets/1005050/20140896/08648924-a68e-11e6-8fc6-720a7173e644.png)

So I decided to stay with `navbar` and add custom css for the hover and active effects.

To swtich to `nav-pills`:

``` html
      <header>
        <ul className="nav nav-pills">
          <li>
            <Link to="/">CSPA service app</Link>
          </li>
          <li>
            <Link to="/gsbpm">Search the GSBPM</Link>
          </li>
          <li>
            <Link to="/gsim">Search the GSIM</Link>
          </li>
          <li>
            <Link to="/nsis">NSIs</Link>
          </li>
        </ul>
      </header>
```

**Comment by ghost** [comment]
Plus, we should define more precisely the routing policy and how it relates to the main menu. When we navigate with the gsbpm explorer for instance, and then we select a service, which menu entry should be highlighted ? For now, the highlight is related to the URL (ie. if the url starts with `/gsbpm`, the gsbpm entry will be highlighted).
