### ISSUE TITLE
Sort GSBPM phases and sub-processes

### ISSUE THREAD

**Issue by FranckCo** [UNECE/Model-Explorer#19]
In the GSBPM overview (/gsbpm), phases should be ordered: 1 to 7 from left to right. Under each phase, subprocesses should be ordered from top to bottom.

**Comment by ghost** [comment]
I don't get it. Here's how it looks like on my computer:

<img width="1234" alt="screen shot 2016-11-12 at 07 05 35" src="https://cloud.githubusercontent.com/assets/1005050/20236051/dc3094c2-a8a6-11e6-9fa5-ce92005e5da7.png">

**Comment by ghost** [comment]
Fixed with 8d374d1eaa54af188d64490a1ac57a7794bc877a. Implementation of sorting was wrong, it worked by chance in Chrome and Firefox, but it didn't work with Edge.
